### ISSUE TITLE
auto rotation hammerhead not working

### ISSUE THREAD

**Issue by imagenoise** [omnirom/android_kernel_lge_hammerhead#1]
auto rotation on hammerhead not working in release du_hammerhead_20140131-2238. tuning it off an on again in quick settings and/or via display in settings doesn't help, reboot neither.

**Comment by xplodwild** [comment]
1) totally unrelated repository
2) this isn't even an official omnirom build you're talking about

**Comment by imagenoise** [comment]
argh, followed wrong link in xda post, sorry!
