### ISSUE TITLE
kitkat-mr2 kernel & RGB KCAL Tuning

### ISSUE THREAD

**Issue by savoca** [omnirom/android_kernel_lge_hammerhead#2]
These got buried on gerrit, but it brings this kernel back up to speed with Google. Also the RGB control goes hand in hand with gamma.

https://gerrit.omnirom.org/#/c/7898/
https://gerrit.omnirom.org/#/c/7897/

**Comment by Entropy512** [comment]
We do not use Github for code submissions or issue tracking.

gerrit.omnirom.org for code submission
jira.omnirom.org for issue tracking

**Comment by savoca** [comment]
Hello me from 9 months ago. Sorry I don't think I even knew how to use gerrit then. Oops.
