### ISSUE TITLE
continous error

### ISSUE THREAD

**Issue by ajmtrz** [omnirom/android_kernel_lge_hammerhead#3]
logcat:
E/qcom_sensors_hal(  930): hal_process_report_ind: Bad item quality: 11

**Comment by xplodwild** [comment]
1. This has nothing to do with kernel
2. This happens on AOSP/Google builds too
3. Bug reports (and that's not a bug) goes to Jira
4. logcat | grep -v qcom_sensors_hal  if it bothers you that much
5. Ask qualcomm for source code and remove that error (which is more of a warning)
6. If you want spam, ever tried to launch camera and looked at logs?

**Comment by ajmtrz** [comment]
ok, thanks
